bhcsc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
# -*-coding:utf-8-*-
from django.urls import path

from . import views

app_name= 'blog'
urlpatterns = [
        path('qft',views.qft,name='qft'),
        path('',views.index,name='index'),
        path('guide_bulletin',views.guide_bulletin,name='guide_bulletin'),
        path('register',views.register,name='register'),
        path('login',views.login,name='login'),
        path('logout',views.logout,name='logout'),
        path('article_detail/<int:article_id>',views.article_detail,name='article_detail'),
        path('post_comment/<int:article_id>',views.post_comment,name='post_comment'),
        path('delete_comment/<int:comment_id>',views.delete_comment,name='delete_comment'),
        path('create_article',views.create_article,name='create_article'),
        path('update_article/<int:article_id>',views.update_article,name='update_article'),
        path('delete_article/<int:article_id>',views.delete_article,name='delete_article'),
        path('profile/<str:username>',views.profile,name='profile'),
        path('edit_profile',views.edit_profile,name='edit_profile'),
        path('reset_password',views.reset_password,name='reset_password'),
        ]

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class User(models.Model):
    # ID自动创建
    # 用户名不可重复
    username = models.CharField(max_length=50, unique=True, verbose_name='用户名')
    signature = models.CharField(max_length=50 ,verbose_name='个性签名',blank=True,default='')
    email = models.CharField(max_length=100, verbose_name='邮箱')
    password = models.CharField(max_length=100, verbose_name='密码字段')
    # 状态有正常'A',封禁'B',已注销'C'
    # 用户注销后，数据库并不会删除此用户，只是将该用户状态修改为'closed'
    class StatusList(models.TextChoices):
            ACTIVITY = 'A', '正常'
            BANNED = 'B', '封禁中'
            CLOSE = 'C', '已注销'
    status = models.CharField(max_length=1, verbose_name='状态',choices=StatusList.choices,default=StatusList.ACTIVITY)

    def __str__(self):
        return self.username


class Article(models.Model):
    # ID自动创建
    # 因为作者不会被删除(至少项目构思之初是这样想的)，
    # 所以文章在作者注销账号后，依然会存在于数据库
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='文章作者')
    title = models.CharField(max_length=100,db_index=True, verbose_name='标题')
    body = models.TextField(verbose_name='正文')
    codehilite_style = models.CharField(max_length=25, verbose_name='代码高亮主题',default='solarized-light')
    created = models.DateTimeField(default=timezone.now, verbose_name='创建时间')

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True,verbose_name='更新时间')
    visible =models.BooleanField(verbose_name='可见',default=True)
    censored =models.BooleanField(verbose_name='已审核',default=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    # ID自动创建
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name='评论的文章')
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='评论用户')
    body=models.TextField(max_length=3000,verbose_name='评论内容')
    created = models.DateTimeField(default=timezone.now, verbose_name='创建时间')

    def __str__(self):
        return self.user.username+':'+self.body[:20]

class SessionLog(models.Model):
    username=models.CharField(max_length=20,verbose_name='用户名')
    server_name=models.CharField(max_length=100,verbose_name='访问地址')
    ip=models.CharField(max_length=16,verbose_name='IP')
    time = models.DateTimeField(default=timezone.now, verbose_name='访问时间')
    def __str__(self):
        return self.ip+' '+self.username+' '+self.time.strftime('%Y-%m-%d %H:%M:%S')+' '+self.server_name

blog/views.py
import django
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import timezone
from django.db.utils import DataError
from django.urls import reverse
from django.contrib.auth import hashers
from django.core import mail,cache
from django.db.models import Q
from . import models
import random
import string
import datetime
import markdown
import random
from django.conf import settings
import sys
# Create your views here.




def check_logged_in(func):
    # 检查用户是否登录了
    def wrapper(*args, **kw):
        # FOR DEBUG
        print("args:", args)
        print("kw:", kw)
        request = args[0]
        if 'username' not in request.session:
            #           context = {'the_url': reverse('blog:index'),
            #                      'hint': '你还没登录',
            #                      'page': '主页',
            #                      }
            #           return render(request, 'blog/hint.html', context)
            return hint_and_redirect(request, reverse('blog:index'), '你还没登录,正在返回主页')
        return func(*args, **kw)
    return wrapper


def send_verify_code(request, to_email):
    # 因为是发验证码，所以要有一个过期时间，这里设为5min后过期
    # 如果使用普通的个人邮箱，会有每日发送限制和被锁定的可能
    print("DEBUG MAIL",to_email)
    request.session.set_expiry(60*5)
    verify_code = random.randint(100000, 999999)
    request.session['verify_code'] = str(verify_code)
    msg = '您的验证码为 '+str(verify_code)+' ，请在五分钟内输入'
    mail.send_mail('您的验证码', msg, settings.EMAIL_HOST_USER, [to_email])

# 以下是视图

#@django.views.decorators.cache.cache_page(30)
def qft(request):
    # quick feature test
    if cache.cache.get('time_now_qft') == None:
        print("DEBUG",'读取了缓存')
        time_now_qft=timezone.now()
        cache.cache.set('time_now_qft',time_now_qft)
    else:
        print("DEBUG",'读取了缓存')
        time_now_qft=cache.cache.get('time_now_qft')


    return HttpResponse(time_now_qft)



def guide_bulletin(request):
    # 硬编码一篇文章，指定为网站公告
    return article_detail(request,15)

def hint_and_redirect(request, the_url, hint, show_hint=True, delay_time=1000):
    if show_hint == False:
        return redirect(the_url)
    else:
        context = {'the_url': the_url,
                   'hint': hint,
                   'delay_time': delay_time,
                   }
        return render(request, 'blog/hint.html', context)



def index(request):
    if 'search_text' in request.GET and request.GET.get('search_text').split() != []:
        search_text = request.GET.get('search_text')
        articles = models.Article.objects.filter(Q(title__icontains=search_text) | Q(
            body__icontains=search_text)).filter(visible=True)

        context = {'articles': articles,
                   'searched': 'yes'
                   }
    else:
        articles = models.Article.objects.order_by('-id').filter(visible=True)
        print(articles)
        context = {'articles': articles,
                   'searched': 'no'
                   }
    # 截取文章开头一部分作为预览
    for a in context['articles']:
        a.body = a.body[:200]
        if len(a.body) == 100:
            a.body += '...'

    return render(request, 'blog/index.html', context)


def article_detail(request, article_id):

    article = get_object_or_404(models.Article, id=article_id)
    try:
        comments= models.Comment.objects.filter(article=article)
        print("DEBUG",comments)
    except models.Comment.DoesNotExist:
        comments=None
    if article.visible == False and 'username' not in request.session:
        raise Http404()
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                     ])
    if comments != None:
        for c in comments:
            c.body = markdown.markdown(c.body,
                                             extensions=[
                                                 # 包含 缩写、表格等常用扩展
                                                 'markdown.extensions.extra',
                                                 # 语法高亮扩展
                                                 'markdown.extensions.codehilite',
                                             ])

    context = {'article': article,
            'comments':comments}
    return render(request, 'blog/article_detail.html', context)


@check_logged_in
def post_comment(request, article_id):

    if request.method == 'POST':
        article = get_object_or_404(models.Article, id=article_id)
        user = get_object_or_404(models.User, id=request.session.get('id'))
        body = request.POST.get('body')
        if body.split() == []:
            return hint_and_redirect(request, reverse('blog:article_detail',args=[article_id]), '评论不能为空')

        new_comment = models.Comment()
        new_comment.article = article
        new_comment.user = user
        new_comment.body = body

        try:
            new_comment.save()
            return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '评论成功',False)
        except DataError:
            return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '数据错误，请检查内容重新发送')
        except:
            return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '未知错误')

    # 处理错误请求
    else:
        return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '评论只支持POST形式发送')


@check_logged_in
def delete_comment(request,comment_id):
    # 之所以用GET方法，完全是因为在前端方便写
    if request.method == 'GET':
        print('收到了get方法')
        print(request.GET.get('delete_comment'))
        if request.GET.get('delete_comment') == 'yes':
            print('DEBUG')
            comment=get_object_or_404(models.Comment,id=comment_id)
            article_id=comment.article.id
            if request.session.get('id') == comment.user.id:
                print("DEBUG session id 和 comment user id 一样")
                comment.delete()
                return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '删除评论成功')
            else:
                return hint_and_redirect(request, reverse('blog:article_detail', args=[article_id]), '您不是评论用户本人，删除评论失败')



def profile(request, username):
    user = get_object_or_404(models.User, username=username)
    user.status = models.User.StatusList(user.status).label
    articles = models.Article.objects.filter(
        author__username=username)

    # 本人登录后浏览个人主页
    if request.session.get('id') == user.id:
        # 为了方便，将状态值的人类可读名称直接赋值给status，方便前台调用
        context = {'articles': articles,
                   'user': user,
                   'is_self': 'yes',
                   }
        return render(request, 'blog/profile.html', context)
    else:
        context = {'articles': articles,
                   'user': user,
                   'is_self': 'no',
                   }
        return render(request, 'blog/profile.html', context)


@check_logged_in
def edit_profile(request):
    try:
        user = models.User.objects.get(id=request.session.get('id'))
    except models.User.DoesNotExist:
        #       context = {'the_url': reverse('blog:index'),
        #                  'hint': '未知错误,可能会话已过期，请尝试重新登录',
        #                  'page': '主页',
        #                  }
        #       return render(request, 'blog/hint.html', context)
        return hint_and_redirect(request, reverse('blog:index'), '未知错误，可能会话已过期，请尝试重新登录')
    if request.method == 'GET':
        context = {'user': user,
                   }
        return render(request, 'blog/edit_profile.html', context)
    elif request.method == 'POST':

        current_username = request.session.get('username')
        username = request.POST.get('username')
        email = request.POST.get('email')
        signature = request.POST.get('signature')
        # 下面的try块代码可能看着很乱，其实很简单，就是如果未改名,
        # 则会执行finally块内容，也就是成功保存。若是改名了，这会
        # 查找是否有同名用户，有的话就会直接return提示信息到前端，
        # 若是无同名用户，则会抛出找不到用户的异常，然后被捕获异常
        # 然后执行finally块内容
        try:
            # 检测数据库中是否已存在同名用户，若抛出该用户
            # 名不存在异常，则为可以存入数据库
            if current_username != username:
                models.User.objects.get(username=username)
                context = {'err_msg': '此用户名已存在，请更换一个',
                           'user': user,
                           }
                return render(request, 'blog/edit_profile.html', context)
        except models.User.DoesNotExist:
            pass
        finally:
            user.username = username
            user.email = email
            user.signature = signature

        try:
            user.save()
            # 修改成功
#           context = {'the_url': reverse('blog:profile'),
#                      'hint': '修改个人资料成功了',
#                      'page': '个人中心',
#                      }
#           return render(request, 'blog/hint.html', context)
            request.session['username'] = user.username
            return hint_and_redirect(request, reverse('blog:profile', args=[request.session.get('username')]), '修改个人资料成功', False)
        except DataError:
            context = {'err_msg': '数据错误，请检查您输入的内容是否符合格式',
                       }
            return render(request, 'blog/register.html', context)
        except:
            return hint_and_redirect(request, reverse('blog:edit_profile'), '未知错误')


@check_logged_in
def create_article(request):
    #   if 'username' not in request.session:
    #       context={'the_url':reverse('blog:index'),
    #               'hint':'你还没登录',
    #               'page':'主页',
    #               }
    #       return render(request,'blog/hint.html',context)

blog/templates/blog/article_detail.html
<!DOCTYPE html>
{% extends "blog/base.html" %}
{% load static %}
{% block extra_head  %}
<!--代码高亮 -->
<link rel="stylesheet" href="{% get_static_prefix  %}md_css/{{article.codehilite_style}}.css">

<style>
blockquote {
	padding: 0 15px;
	color: #777;
	border-left: 4px solid #ddd;
}
</style>
{% endblock  %}

{% block title %}{{article.title}}{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- 展示文章的title -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <!-- 展示文章的author -->
        <div class="alert alert-success">作者：<a href="{% url 'blog:profile' article.author  %}" class="alert-link">{{ article.author }}</a></div>
        <!-- 展示文章author的signature -->
        <div class="alert alert-light">{{ article.author.signature }}</div>
        <div class="col-12"></div>
        <div class="col-3 alert alert-light">创建于 {{ article.created |date:"Y/m/d H:i:s"}}</div>
        <div class="col-3 alert alert-light">更新于 {{ article.updated |date:"Y/m/d H:i:s"}}</div>
        <!-- 文章正文 -->
        {%  if request.session.id == article.author.id  %}
        <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                操作
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'blog:update_article' article.id %}">修改</a>
                <a class="dropdown-item" href="{%  url 'blog:delete_article' article.id %}">删除</a>
            </div>
        </div>
        {% if article.censored == False  %}
        <div class="col-12 alert alert-info">待AI审核</div>
        {% elif article.visible == False  %}
        <div class="col-12 alert alert-warning">AI审核不通过，请修改文章后提交</div>
        {% elif article.visible == True  %}
        <div class="col-12 alert alert-success">AI审核通过</div>
        {% endif  %}
        {% endif  %}
        <div class="col-12 bg-light">
            <p>{{ article.body |safe}}</p>
        </div>
    </div>
    <!--评论版-->
    {% if request.session.id %}
    <div>
        <br/>
        <form action="{% url 'blog:post_comment' article.id %}" method="POST" >
            {% csrf_token %}
            <div class="form-group">
                <label for="body">
                    <strong>
                        评论
                    </strong>
                </label>
                <textarea 
                       type="text" 
                       class="form-control" 
                       name="body" 
                       rows="2"></textarea>
            </div>
            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary ">发送</button>                    
        </form>
    </div>
    <br>
    {% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'blog:login' %}">登录</a>后回复
    </h5>
    <br>
    {% endif %}
    <div>
        {% for comment in comments %}
        <br>

            {% if comment.user == article.author  %}
            <div class="alert alert-success">
                <a href="{% url 'blog:profile' comment.user  %}" class="alert-link">{{ comment.user }}&nbsp
                </a>
                <span style="">
                    {{ comment.created|date:"Y/m/d H:i:s" }}
                </span>
                {% if comment.user.id == request.session.id  %}
                <a href="{% url 'blog:delete_comment' comment.id %}?delete_comment=yes" class="alert-link">&nbsp&nbsp删除
                {% endif  %}
                </a>
            </div>
            {% else  %}
            <div class="alert alert-info">
                <a href="{% url 'blog:profile' comment.user  %}" class="alert-link">{{ comment.user }}&nbsp
                </a>
                <span style="">
                    {{ comment.created|date:"Y/m/d H:i:s" }}
                </span>
                {% if comment.user.id == request.session.id  %}
                <a href="{% url 'blog:delete_comment' comment.id %}?delete_comment=yes" class="alert-link">&nbsp&nbsp删除
                {% endif  %}
                </a>
            </div>
            {% endif  %}
        <div class="col-12 bg-light">
            <p>{{ comment.body |safe}}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

blog/templates/blog/confirm.html
<!DOCTYPE html>
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "blog/base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} {{ question }} {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!--你可能会想，为什么不使用弹窗而是用这种方式确认，原因很简单，因为作者不会JS -->
<div class="container col-4 text-center justify-content-center ">
<form action="#" class="form-signin " method="POST">
{% csrf_token %}
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="Check1" name="confirm" value="yes">
    <label class="form-check-label" for="Check1"  >{{ question }}</label>
  </div>
  <button type="submit" class="btn btn-primary">提交</button>
</form>
</div>
{% endblock content %}

blog/templates/blog/edit_profile.html
<!DOCTYPE html>
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "blog/base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交新资料的表单 -->
            {%  if err_msg  %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{err_msg}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif  %}
            <form method="POST" action="#">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">用户名</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="username" value={{user.username}} >
                </div>
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">邮箱</label>
                        <!-- 文本框 -->
                        <input type="email" class="form-control" id="title" name="email" value={{user.email}} >
                    </div>
                        <div class="form-group">
                            <!-- 标签 -->
                            <label for="title">个性签名</label>
                            <!-- 文本框 -->
                            <input type="text" class="form-control" id="title" name="signature" value={{user.signature}} >
                        </div>
                            <!-- 提交按钮 -->
                            <button type="submit" class="btn btn-primary">保存资料</button>

            </form>
            <br>
            <a href="{% url 'blog:reset_password'  %}" class="btn btn-primary" role="button" aria-pressed="true">修改密码</a>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/footer.html
<!DOCTYPE html>
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark ">
    <div class="container">
        <p class="m-0 text-center text-white"><a class="text-muted" href="#" title="还没上传" >项目源代码</a></p>
    </div>
</footer>

blog/templates/blog/header.html
<!DOCTYPE html>
<!-- 定义导航栏 -->
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top"> <a class="navbar-brand" href="{% url 'blog:index'  %}" title="点击可以返回主页">Django博客测试</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item "> <a class="nav-link" href="{% url 'blog:guide_bulletin'  %}">网站公告</a> </li>
      <li class="nav-item "> <a class="nav-link" href="{% url 'blog:qft'  %}">快速功能测试</a> </li>
    </ul>
    <form action="#" method="GET" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 bg-dark text-white" type="text" name="search_text" placeholder="搜索文章标题或内容" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit"> 搜 索 </button>
    </form>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active"> <a class="nav-link" href="{%  url 'blog:create_article'  %}" >写文章</a> </li>
        {%  if request.session.username  %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.session.username}}</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'blog:profile' request.session.username  %}">个人中心</a>
          <a class="dropdown-item" href="{%  url 'blog:logout'  %}">登出</a>
        </div>
      </li>
        {%  else  %}
        <li class="nav-item active"> <a class="nav-link" href="{%  url 'blog:login'  %}">登录</a> </li>
        {% endif  %}
    </ul>
  </div>
</nav>
<div>
    <br><br><br>
</div>

blog/templates/blog/hint.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <p style='font-size:30px;color:#2e5c6e;font-weight:bold'>{{hint}}</p>
        <!-- 上面显示完提示信息后，将会跳转到the_url，时间大概是3s -->
        <script type="text/javascript">
            setTimeout("window.location.replace('{{the_url}}')",{{delay_time}});
        </script>

    </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "blog/base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}首页:文章列表{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->



<div class="container-fluid">
    {% if searched == "yes"  %}
    <h3 class="col-12">搜索结果</h3>
    {% else  %}
    <h3 class="col-12">最新文章</h3>
    {% endif  %}
    <div class="row mt-2">
        <div class="col-12">
            {% if articles  %}

            {% for article in articles %}
            <!-- 文章内容 -->
            <div class="col-12 mb-4 ">
                <!-- 卡片容器 -->
                <div class="card h-100">
                    <!-- 标题 -->
                    <h4 class="card-header">{{ article.title }}</h4>
                    <!-- 摘要 -->
                    <div class="card-body">
                        <p class="card-text">{{article.author.username}}: {{ article.body }}</p>
                    </div>
                    <!-- 注脚 -->
                    <div class="card-footer">
                        <a href="{% url 'blog:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                    </div>
                </div>
            </div>

            {% endfor %}
            {% else  %}
            <h6 class="col-12 text-secondary">无</h6>

            {% endif  %}
        </div>
    </div>
</div>

</div>
</div>
{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container col-4 text-center justify-content-center ">
<form action="#" class="form-signin " method="POST">
{% csrf_token %}
      <h1 class="h1 mb-3 font-weight-normal">登录</h1>
      <h6 class="h6 mb-3 font-weight-normal">未有账号? 点击<a href="{%  url 'blog:register'  %}">这里</a>注册</h6>
      <input type="email" name="email" class="form-control" placeholder="邮箱" required >
      <input type="password" name="password1" class="form-control" placeholder="密码" required>
      <button class="btn btn-lg btn-dark btn-block" type="submit">登录</button>
</form>
      <p class="mt-3 h9 font-weight-normal">忘记密码? 点击<a href="{%  url 'blog:reset_password'  %}">这里</a>重置</p>
{%  if err_msg  %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{err_msg}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
{%  endif  %}
</div>
{% endblock content %}

blog/templates/blog/qft.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
{% load static %}
    <title></title>
<style>
blockquote {
	padding: 0 15px;
	color: #777;
	border-left: 4px solid #ddd;
}
</style>
<link rel="stylesheet" href="{% get_static_prefix  %}md_css/{{article.codehilite_style}}.css">
</head>
<body>
    
            <p>{{ article.body |safe}}</p>
</body>
</html>

blog/templates/blog/register2.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
    <title>用户注册</title>
    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'blog/style.css' %}"> 
</head>
<body>
    <a class='homepage' href='{%  url 'blog:index'  %}'>首页</a>
<form action="{% url 'blog:register' %}" method='POST'>
{% csrf_token %}
        <p>用户名<input type='text' name='username' value='' /></p>
        <p>邮箱<input type='text' name='email' value='' /></p>
        <p>密码<input type='password' name='password1' value='' /></p>
        <p>重复密码<input type='password' name='password2' value='' /></p>
        <p style="color:red">{{err_msg}}</p>
        <input type='submit' value='注册' />
    </form>
</body>
</html>